import type { CampaignCase, CampaignCaseProgress } from '../campaign/types';
import { hasRequiredEvidence } from '../systems/campaign';
import { icon } from './icons';

export type NotebookTab = 'evidence' | 'connections' | 'tasks' | 'history';
const escape = (value: string): string => value.replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]!);

/** Digital notebook panels read actual campaign data and never award progress. */
export function renderNotebook(level: CampaignCase, progress: CampaignCaseProgress | null, mission: string, tab: NotebookTab): string {
  const inspected = progress?.inspectedIds ?? [];
  const tabs: [NotebookTab, string][] = [['evidence', 'Улики'], ['connections', 'Связи'], ['tasks', 'Задания'], ['history', 'История']];
  const navigation = `<div class="notebook-tabs" role="tablist" aria-label="Разделы блокнота">${tabs.map(([id, title]) => `<button class="notebook-tab" role="tab" id="notebook-tab-${id}" aria-selected="${tab === id}" aria-controls="notebook-panel" data-action="notebook-tab" data-tab="${id}">${title}</button>`).join('')}</div>`;
  let body = '';
  if (tab === 'evidence') body = `<div class="notebook-grid">${level.equipment.map((device) => `<div class="notebook-evidence"><button class="evidence-item ${inspected.includes(device.id) ? 'found' : ''}" data-action="evidence" data-id="${device.id}" ${inspected.includes(device.id) ? '' : 'disabled'}><span class="evidence-icon">${icon(device.category)}</span><span>${escape(device.shortName)}<small>${inspected.includes(device.id) ? 'Характеристики и наблюдение' : 'Подойдите и осмотрите в комнате'}</small></span>${icon(inspected.includes(device.id) ? 'check' : 'lock')}</button>${inspected.includes(device.id) ? `<button class="suspect-tag ${progress?.taggedEquipmentIds.includes(device.id) ? 'tagged' : ''}" data-action="tag-evidence" data-id="${device.id}">${progress?.taggedEquipmentIds.includes(device.id) ? 'Подозрение отмечено' : 'Отметить подозрение'}</button>` : ''}</div>`).join('')}</div>`;
  if (tab === 'connections') body = `<div class="evidence-connections"><h3>Сопоставление источников</h3>${level.analysis.map((question) => `<div><span>${(question.evidenceIds ?? []).map((id) => escape(level.equipment.find((device) => device.id === id)?.shortName ?? id)).join(' ↔ ')}</span><p>${escape(question.prompt)}</p><small>${progress?.analysisSolved ? `✓ ${escape(question.explanation)}` : 'Исследуйте эти источники, затем проверьте вывод в анализе.'}</small></div>`).join('')}</div>`;
  if (tab === 'tasks') {
    const missing = level.requiredDeviceIds.filter((id) => !inspected.includes(id));
    body = `<div class="notebook-task"><span class="chip">ТЕКУЩАЯ ЦЕЛЬ</span><h3>${escape(mission)}</h3><p>Собрано ${inspected.length}/${level.equipment.length} источников. Для отчёта требуется ${level.requiredEvidence} и все ключевые данные.</p>${missing.length ? `<p>Ключевые источники: ${missing.map((id) => escape(level.equipment.find((device) => device.id === id)?.shortName ?? id)).join(', ')}.</p>` : '<p>Все ключевые источники записаны.</p>'}<ol><li>${progress && hasRequiredEvidence(level, progress) ? '✓' : '○'} Исследование</li><li>${progress?.analysisSolved ? '✓' : '○'} Сопоставление данных</li><li>${progress?.reportSolved ? '✓' : '○'} Гипотеза</li><li>${progress?.completed ? '✓' : '○'} Безопасный план</li></ol><p>Дополнительная задача: найдите все источники и сравните альтернативные безопасные планы. XP за найденную улику начисляется один раз.</p></div>`;
  }
  if (tab === 'history') body = `<div class="notebook-history"><h3>Журнал дела ${String(level.order).padStart(3, '0')}</h3>${inspected.length ? inspected.map((id, index) => `<p><span>${String(index + 1).padStart(2, '0')}</span> Записано: ${escape(level.equipment.find((device) => device.id === id)?.shortName ?? id)}</p>`).join('') : '<p>Наблюдений пока нет. Осмотрите источник и нажмите «Записать улику».</p>'}<p>Анализ: ${progress?.analysisAttempts ?? 0} проверок${progress?.analysisSolved ? ', подтверждён' : ''}.</p><p>Гипотеза: ${progress?.reportAttempts ?? 0} проверок${progress?.reportSolved ? ', подтверждена' : ''}.</p><p>План: ${progress?.puzzleAttempts ?? 0} проверок${progress?.completed ? ', принят' : ''}.</p>${progress ? `<small>Последнее сохранение: ${new Date(progress.updatedAt).toLocaleString('ru-RU')}</small>` : ''}</div>`;
  const report = progress && (hasRequiredEvidence(level, progress) || progress.completed) ? `<button class="button primary" data-action="report">${progress.completed ? 'Итоговый отчёт' : !progress.analysisSolved ? 'Анализ улик' : !progress.reportSolved ? 'Гипотеза' : 'План решения'} ${icon('arrow')}</button>` : '';
  return `${navigation}<div class="notebook-panel" id="notebook-panel" role="tabpanel" aria-labelledby="notebook-tab-${tab}">${body}</div><div class="modal-actions"><button class="button secondary" data-action="close">В локацию</button>${report}</div>`;
}
